baseURL = "https://curagua.com.ve/"
languageCode = "es"
paginate = 9
theme = "portio"
title = "Curagua Maquinarias"
# Main Menu
[[menu.main]]
name = "Inicio"
url = "#home"
weight = 1
[[menu.main]]
name = "Servicios"
url = "#service"
weight = 2
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 3
[[menu.main]]
name = "Nosotros"
url = "#about"
weight = 4
[[menu.main]]
name = "Contacto"
url = "#contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "Sobre mi"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Política de privacidad"
url = "#"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Curagua Invest Group, S. A. 2021"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Calle José Iraides Bastardo, mini CC Soleida, local 02, Aguasay - Venezuela."
email = "maquinarias@curagua.com.ve"
openingHours = "De Lunes a Viernes de 8:00 AM a 12:00 M y de 2:00 PM a 6:00 PM"
phone = "+(58) 414 878 0413"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
